### ISSUE TITLE
Allow local config with .forego

### ISSUE THREAD

**Issue by joeyespo** [ddollar/forego#32]
I'm currently using Foreman's `.foreman` file to override the default port without having to run the command differently.

It'd be great to have forego allow the same thing. Either by reading `.forman` or reading from a new `.forego` file.

**Comment by ryansouza** [comment]
Likely the hardest part is going to be finding a yaml parser.

- https://github.com/go-yaml/yaml looks nice but I don't think LGPL is compatible with forego's Apache 2 licsense.
- https://code.google.com/p/goyaml/ has no examples on how to use it, and I couldn't figure it out from reading the code briefly
- others with pros/cons at http://sweetohm.net/html/go-yaml-parsers.en.html

@ddollar would you consider `.forego.json` or `.forego` and just roll with a json config file? I'm assuming that since this is marked enhancement compatibility with foreman's config file isn't that important of a behavior

**Comment by joeyespo** [comment]
@ryansouza It looks like the libraries [are compatible](http://stackoverflow.com/questions/1174240/apache-and-lgpl-license-compatibility) since LGPLv3 and Apache 2.0 are compatible. Just as long as proprietary software that uses forego doesn't modify the yaml library's code.

**Comment by lxfontes** [comment]
have a few spare cycles this week. I can jump on it if nobody is preparing a pr

**Comment by joeyespo** [comment]
I haven't gotten to this yet. Go for it :+1:

**Comment by bsideup** [comment]
@ddollar @voanhduy1512 any news on this?

**Comment by voanhduy1512** [comment]
You could try my branch, i think it works :D
