### ISSUE TITLE
Should env defined variables override .env?

### ISSUE THREAD

**Issue by nvartolomei** [ddollar/forego#85]
This is what I expected actually.

**Comment by ddollar** [comment]
I think this could easily lead to unexpected scenarios. Could you provide an example of this please?

**Comment by BaxterStockman** [comment]
Although this issue is closed, it's perhaps worth mentioning that what the OP expects is [dotenv's default behavior](https://github.com/bkeepers/dotenv#why-is-it-not-overriding-existing-env-variables), justified on the assumption that

> the deployment environment has more knowledge about configuration than the application does.

Maybe this behavior could be optional -- say, via a flag like `--preserve-env`?  I would be happy to submit a PR adding this feature.
